sudo: false

language: php

cache:
  apt: true
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
    - php: hhvm-3.18
      sudo: required
      dist: trusty
      group: edge
    - php: 5.6
    - php: 7.0
    - php: 7.1
    - php: 7.2
    - php: 7.3
    - php: nightly
  fast_finish: true
  allow_failures:
    - php: nightly

before_script:
  - phpenv config-add php-extensions.ini
  - composer install

script: ./vendor/bin/phpunit
